#!/bin/bash
# Use this script to put all of the bits in place to deploy a class
# First we need to install git
sudo zypper install -y git
# now we create the proper directories
mkdir ~/lab_setup ~/az_config
# here we are going to clone ron's projects into the appropriate folder
# these projects are needed as they provide the scripts needed to configure your station and to deploy a class in azure
cd ~/lab_setup
git clone https://github.com/roncterry/install_lab_env
git clone https://github.com/roncterry/configure-as-labmachine
git clone https://github.com/roncterry/create-azure-vm
git clone https://github.com/roncterry/azure-course-tools
# now we need to install the azure-cli package from the microsoft repository
cd ~
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
sudo zypper install -y --from azure-cli azure-cli
# now we can grab the rest of the needed files
git clone https://github.com/aksoutherland/az_config
cd ~/az_config
# now we are going to put the scripts into the correct folder and make them executable
mv bin/* ~/bin
sudo chmod +x ~/bin/*
# some of ron's original files have been changed, here we copy the changed files over the original files
cp modified/copy-image-to-new-azure-container.sh /home/$USER/lab_setup/azure-course-tools/copy-image-to-new-azure-container.sh
cp modified/create-azure-vm.sh /home/$USER/lab_setup/create-azure-vm/create-azure-vm.sh
cp modified/create-course-env-in-azure.sh /home/$USER/lab_setup/azure-course-tools/create-course-env-in-azure.sh
cp modified/get-azure-storage-key.sh /home/$USER/lab_setup/azure-course-tools/get-azure-storage-key.sh
cp modified/show-image-copy-status.sh /home/$USER/lab_setup/azure-course-tools/show-image-copy-status.sh
# you now have everything needed to be able to deploy classes in azure
# for these script to work, you will need to authenticate to azure using "az login"
