#!/bin/bash
# Use this script to put all of the bits into place to deploy a class
# First we need to install git
sudo zypper install -y git
# now we create the proper directories
mkdir ~/lab_setup ~/az_config
# here we are going to clone ron's projects into the appropriate folder
# these folders are needed as they provide the scripts needed to configure your station and to deploy a class in azure
cd ~/lab_setup
git clone https://github.com/roncterry/install_lab_env
git clone https://github.com/roncterry/configure-as-labmachine
git clone https://github.com/roncterry/create-azure-vm
git clone https://github.com/roncterry/azure-course-tools
# now we need to install the azure-cli package from the microsoft repository
cd ~
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
sudo zypper install --from azure-cli azure-cli
# now we can grab the rest of the needed files
git clone https://github.com/aksoutherland/az_config
cd ~/az_config
# now we are going to put the appropriate files in the correct folder and set them as executable
mv bin/* ~/bin
sudo chmod +x bin/*

