#!/bin/bash
# this script will allow you to create/list/revert/delete vm snapshots
# here he will grab our command line values
# $1 is the action we wish to use
# $2 is the name of the snapshot we are working with
# $3 is the description of the snapshot to be created
ACTION="$1"
SNAPNAME="$2"
DESCRIPTION="$3"
usage () {
        echo
        echo "USAGE: $0 <ACTION> <SNAPSHOT_NAME> <DESCRIPTION>"
        echo
        echo "When running this script, you need to supply up to 3 arguments <ACTION> <SNAPSHOT_NAME> <DESCRIPTION>"
        echo 
        echo "<ACTION> will be one of the following create / delete / list / revert"
	echo
	echo "<SNAPSHOT_NAME> should be the name of the snapshot you are creating/deleting/reverting"
	echo
        echo "<DESCRIPTION> should be the description of the snapshot you are creating"
	echo	
        echo "Please re-run the command with the proper arguments"
        echo
        echo "EXAMPLE COMMAND: snapshot create mysnapshot my-description / snapshot delete mysnapshot / snapshot revert mysnapshot / snapshot list"
        echo
}
# We set the variables if they are not specified when the command is run
if [ -z "$3" ]
then
	DESCRIPTION=pre-class
fi

if [ -z "$2" ]
then
        SNAPNAME=snap01
fi


case $1 in
create)
# here we create and list the snapshots
	echo 
	for NAME in $(virsh list --all | awk '{print $2}'| grep -v Name) ; do virsh snapshot-create-as --domain $NAME --name "$SNAPNAME" --description "$DESCRIPTION"; done
	for NAME in $(virsh list --all | awk '{print $2}'| grep -v Name) ; do virsh snapshot-list $NAME ; done
	;;
delete)
# here we delete and list the snapshots
	echo
	for NAME in $(virsh list --all | awk '{print $2}'| grep -v Name) ; do virsh snapshot-delete --domain $NAME "$SNAPNAME" ; done
	for NAME in $(virsh list --all | awk '{print $2}'| grep -v Name) ; do virsh snapshot-list $NAME ; done
	;;
list)
# here we list the snapshots

        echo
	for NAME in $(virsh list --all | awk '{print $2}'| grep -v Name) ; do virsh snapshot-list $NAME ; done
	;;
revert)
# here we revert and list the snapshots
        echo
	for NAME in $(virsh list --all | awk '{print $2}'| grep -v Name) ; do virsh snapshot-revert --domain $NAME "$SNAPNAME" ; done
	for NAME in $(virsh list --all | awk '{print $2}'| grep -v Name) ; do virsh snapshot-list $NAME ; done
	;;
*)
        echo
        usage
        exit
	;;
esac
